# Generated by Django 3.0.8 on 2020-08-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='tell us about yourself'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='business name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_url',
            field=models.CharField(blank=True, default='Paste your LinkedIn URL here', max_length=200, verbose_name='linkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='placeholder-1.jpg', upload_to='profile_photo/', verbose_name='profile photo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('Founder', 'Founder'), ('Partner', 'Partner'), ('Mentor', 'Mentor'), ('Team', 'Flair Team'), ('Advocate', 'Advocate')], default='Founder', max_length=20, verbose_name='family member type'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last name'),
        ),
    ]
