# Generated by Django 3.0.8 on 2020-08-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200826_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(default='placeholder-1.jpg', upload_to='profile_photo/', verbose_name='profile photo'),
        ),
    ]
