# Generated by Django 3.0.8 on 2020-08-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200825_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='type',
            field=models.CharField(choices=[('Founder', 'Founder'), ('Partner', 'Partner'), ('Mentor', 'Mentor'), ('Team', 'Flair Team'), ('Advocate', 'Advocate')], default='Founder', max_length=20, verbose_name='family member type'),
        ),
    ]
