# Generated by Django 3.0.8 on 2020-08-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='linkedIn profile URL'),
        ),
    ]
