# Generated by Django 3.0.8 on 2020-09-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='category',
        ),
    ]
