# Generated by Django 3.0.8 on 2020-09-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_newsstory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(default='Type of Story', max_length=20, verbose_name='story category'),
        ),
    ]
