# Generated by Django 3.0.8 on 2020-09-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsstory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstory',
            old_name='category',
            new_name='story_category',
        ),
    ]
