# Generated by Django 3.0.8 on 2020-09-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200904_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstory',
            old_name='story_category',
            new_name='category',
        ),
    ]
