# Generated by Django 3.0.8 on 2020-08-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200822_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='linkedin_url',
            field=models.CharField(default='https://www.linkedin.com/company/canvascoworking', max_length=200, verbose_name='LinkedIn Profile URL'),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Input By'),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Type of Family Member'),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='content',
            field=models.TextField(verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.ImageField(default='placeholder-1.jpg', upload_to='static/news/images', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='title',
            field=models.CharField(max_length=200, verbose_name="Individual's Name"),
        ),
    ]
