# Generated by Django 3.0.8 on 2020-09-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200904_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='linkedin_url',
        ),
    ]
