# Generated by Django 3.0.8 on 2020-08-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200822_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Founder', 'Founder'), ('Partner', 'Partner'), ('Mentor', 'Mentor'), ('Team', 'Flair Team'), ('Advocate', 'Advocate')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='newsstory',
            name='category',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.ManyToManyField(to='news.Family'),
        ),
    ]
