# Generated by Django 3.0.8 on 2020-08-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200822_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='type',
            field=models.CharField(choices=[('Founder', 'Founder'), ('Partner', 'Partner'), ('Mentor', 'Mentor'), ('Team', 'Flair Team'), ('Advocate', 'Advocate')], default='Founder', max_length=20),
        ),
    ]
