# Generated by Django 3.0.8 on 2020-09-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_newsstory_linkedin_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='type',
        ),
    ]
