# Generated by Django 3.0.8 on 2020-08-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200823_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='category',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(default='Good News Story', max_length=20, verbose_name='Story Category'),
        ),
    ]
