# Generated by Django 3.0.8 on 2020-08-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20200823_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.ImageField(default='placeholder-1.jpg', upload_to='story_image/', verbose_name='story photo'),
        ),
    ]
